/**
 * RAP-only ts-xsd Codegen Configuration
 *
 * Generates typed schemas for RAP (RESTful ABAP Programming) only.
 * This is a minimal config that doesn't require SAP base schemas.
 */

import {
  defineConfig,
  rawSchema,
  interfaces,
} from '@abapify/ts-xsd/generators';

const targetSchemas = [
  // Atom namespace (custom standalone version)
  'custom/atom',
  // RAP schemas
  'custom/rap/behaviourdefinition',
  'custom/rap/ddls',
  'custom/rap/rapgenerator',
];

export default defineConfig({
  importExtension: '',
  clean: true,
  sources: {
    xsd: {
      xsdDir: '.xsd',
      outputDir: 'src/schemas/generated/schemas',
      schemas: targetSchemas,
      autoLink: true,
    },
  },
  generators: [
    rawSchema({
      defaultExport: true,
      $xmlns: true,
      $imports: true,
      singleQuote: true,
    }),
    interfaces({
      filePattern: '../types/{name}.types.ts',
      flatten: true,
      addJsDoc: true,
    }),
  ],

  afterAll({ sources }) {
    const allSchemas = sources.xsd.schemas as string[];
    const rapSchemas = allSchemas
      .filter((s: string) => s.startsWith('custom/rap/'))
      .map((s: string) => s.replace('custom/rap/', ''));

    const rapIndex = [
      '/**',
      ' * RAP schemas index',
      ' * DO NOT EDIT - Generated by ts-xsd codegen',
      ' */',
      '',
      ...rapSchemas.map(
        (s: string) =>
          `export { default as ${s.replace(/-/g, '')} } from './rap/${s}';`,
      ),
      '',
    ].join('\n');

    const typedLines: string[] = [
      '/**',
      ' * RAP typed schema exports',
      ' * DO NOT EDIT - Generated by ts-xsd codegen',
      ' */',
      '',
      `import { typedSchema, type TypedSchema } from '@abapify/ts-xsd';`,
      '',
    ];

    const sapTypeImportLines: string[] = [];
    typedLines.push('// Custom RAP schemas');
    for (const schemaName of rapSchemas) {
      const exportName = schemaName.replace(/-/g, '');
      const importName = `_${schemaName.replace(/-/g, '')}`;
      const rootTypeName = `${schemaName.replace(/-/g, '')}Schema`;

      sapTypeImportLines.push(
        `import type { ${rootTypeName} } from './types/custom/rap/${schemaName}.types';`,
      );
      typedLines.push(
        `import ${importName} from './schemas/custom/rap/${schemaName}';`,
      );
      typedLines.push(
        `export const ${exportName}: TypedSchema<${rootTypeName}> = typedSchema<${rootTypeName}>(${importName});`,
      );
    }

    const typeImportLines = [
      `// Pre-generated root schema types`,
      ...sapTypeImportLines,
      '',
    ];
    const sapIndex = typedLines.findIndex(
      (line) => line === '// Custom RAP schemas',
    );
    typedLines.splice(sapIndex, 0, ...typeImportLines);

    return [
      {
        path: 'src/schemas/generated/schemas/custom/rap/index.ts',
        content: rapIndex,
      },
      {
        path: 'src/schemas/generated/rap-typed.ts',
        content: typedLines.join('\n'),
      },
    ];
  },
});
